server:
  port: 8887

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/vanderfan/springcloud-learning
          searchPaths: config
      label: master

eureka:
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/